name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: bash run.sh
      env:
        VUE_APP_IP: ${{ secrets.VUE_APP_IP }}
